stages:
  - release
  - deploy

.base_release: &base_release
  image:
    name: reg.1cb.kz/library/kaniko-project/executor:debug
    entrypoint: [""]
  allow_failure: false

release:dev:
  tags:
    - kube-build
  only:
    - lerna
  stage: release
  environment:
    name: kyc-staging
  variables:
    CONTAINER_TAGGED_IMAGE: $HR_REGISTRY/$CI_PROJECT_NAME-$CI_PROJECT_ID/$CI_PROJECT_NAME:$CI_ENVIRONMENT_SLUG-$CI_PIPELINE_ID
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$HR_REGISTRY\":{\"username\":\"$HR_REGISTRY_USER\",\"password\":\"$HR_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - KANIKOPROXYBUILDARGS="--build-arg BACKEND_URL=$BACKEND_URL"
    - echo $KANIKOPROXYBUILDARGS
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile $KANIKOPROXYBUILDARGS --destination $CONTAINER_TAGGED_IMAGE
  dependencies:
    - build:dev
  <<: *base_release

.base_deploy: &base_deploy
  stage: deploy
  variables:
    CONTAINER_TAGGED_IMAGE: $HR_REGISTRY/$CI_PROJECT_NAME-$CI_PROJECT_ID/$CI_PROJECT_NAME:$CI_ENVIRONMENT_SLUG-$CI_PIPELINE_ID
  tags:
    - kube-build
  before_script:
    - kubectl config use-context autonesie/gitlab-agent:gitlab-agent-k8s-ext-prod
  image: reg.1cb.kz/library/kubectl
  script:
    - kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
    - kubectl create secret docker-registry harbor-$CI_PROJECT_ID --docker-server=$HR_REGISTRY --docker-username=$HR_REGISTRY_USER --docker-password=$HR_REGISTRY_PASSWORD --docker-email=$GITLAB_USER_EMAIL --dry-run=client -o yaml | kubectl -n $NAMESPACE apply -f -
    - cat ./k8s/service.yml | envsubst | kubectl apply -n $NAMESPACE -f -
    - cat ./k8s/deployment.yml | envsubst | kubectl apply -n $NAMESPACE -f -
    - cat ./k8s/ingress.yml | envsubst | kubectl apply -n $NAMESPACE -f -

deploy:dev:
  environment:
    name: kyc-staging
  dependencies: []
  variables:
    REPLICAS: 1
  only:
    refs:
      - lerna
  <<: *base_deploy
