stages:
  - build
  - release
  - deploy

.base_build: &base_build
  only:
    - /lerna^/
  image: reg.1cb.kz/dockerhub/library/node:16.17.1-alpine3.15
  tags:
    - kube-build
  environment:
    name: kyc-staging
  artifacts:
    expire_in: 5 minute

build:dev:
  <<: *base_build
  stage: build-main
  variables:
    CONTAINER_TAGGED_IMAGE: $HR_REGISTRY/$CI_PROJECT_NAME-$CI_PROJECT_ID/$CI_PROJECT_NAME:$CI_ENVIRONMENT_SLUG-$CI_PIPELINE_ID
  script:
#    - npm run build
    - ls -a

.base_release: &base_release
  image:
    name: reg.1cb.kz/library/kaniko-project/executor:debug
    entrypoint: [""]
  allow_failure: false

release:dev:
  tags:
    - kube-build
  only:
    - /lerna^/
  stage: release-main
  environment:
    name: kyc-staging
  variables:
    CONTAINER_TAGGED_IMAGE: $HR_REGISTRY/$CI_PROJECT_NAME-$CI_PROJECT_ID/$CI_PROJECT_NAME:$CI_ENVIRONMENT_SLUG-$CI_PIPELINE_ID
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$HR_REGISTRY\":{\"username\":\"$HR_REGISTRY_USER\",\"password\":\"$HR_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - KANIKOPROXYBUILDARGS="--build-arg BACKEND_URL=$BACKEND_URL --build-arg HOST_MAIN=$HOST_MAIN"
    - echo $KANIKOPROXYBUILDARGS
    - ls -a
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile $KANIKOPROXYBUILDARGS --destination $CONTAINER_TAGGED_IMAGE
  dependencies:
    - build:dev
  <<: *base_release

.base_deploy: &base_deploy
  image: reg.1cb.kz/library/kubectl
  tags:
    - kube-build

deploy:dev:
  only:
    - lerna
  stage: deploy
  dependencies: []
  variables:
    CONTAINER_TAGGED_IMAGE: $HR_REGISTRY/$CI_PROJECT_NAME-$CI_PROJECT_ID/$CI_PROJECT_NAME:$CI_ENVIRONMENT_SLUG-$CI_PIPELINE_ID
  environment:
    name: kyc-staging
  script:
    - ls -a
    - kubectl create secret docker-registry harbor --docker-server=$HR_REGISTRY --docker-username=$HR_REGISTRY_USER --docker-password=$HR_REGISTRY_PASSWORD --docker-email=$GITLAB_USER_EMAIL --dry-run=true -o yaml | kubectl replace --force -f -
    - cat ./k8s/service-main.yml | envsubst | kubectl apply -f -
    - cat ./k8s/deployment-main.yml | envsubst | kubectl apply -f -
    - cat ./k8s/ingress-main.yml | envsubst | kubectl apply -f -
  <<: *base_deploy
