stages:
#  - cache
  - release
  - deploy

#cache:dev:
#  stage: cache
#  script:
#    - echo "This job uses a cache."
#    - ls -a
#  cache:
#    key: node_modules
#    paths:
#      - node_modules

.base_release: &base_release
  image:
    name: reg.1cb.kz/library/kaniko-project/executor:debug
    entrypoint: [""]
  allow_failure: false

release:dev:
  tags:
    - kube-build
  only:
    - /^lerna-.*/
  stage: release
  environment:
    name: kyc-staging
  variables:
    CONTAINER_TAGGED_IMAGE: $HR_REGISTRY/$CI_PROJECT_NAME-$CI_PROJECT_ID/$CI_PROJECT_NAME:$CI_ENVIRONMENT_SLUG-$CI_PIPELINE_ID
  script:
    - ls -a
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$HR_REGISTRY\":{\"username\":\"$HR_REGISTRY_USER\",\"password\":\"$HR_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - KANIKOPROXYBUILDARGS="--build-arg BACKEND_URL=$BACKEND_URL"
    - echo $KANIKOPROXYBUILDARGS
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/packages/main/Dockerfile $KANIKOPROXYBUILDARGS --destination $CONTAINER_TAGGED_IMAGE
  cache:
    key: node_modules
    paths:
      - node_modules
#  dependencies:
#    - build:dev
  <<: *base_release

.base_deploy: &base_deploy
  stage: deploy
  variables:
    CONTAINER_TAGGED_IMAGE: $HR_REGISTRY/$CI_PROJECT_NAME-$CI_PROJECT_ID/$CI_PROJECT_NAME:$CI_ENVIRONMENT_SLUG-$CI_PIPELINE_ID
  tags:
    - kube-build
  image: reg.1cb.kz/library/kubectl
  script:
    - ls -a
    - kubectl create secret docker-registry harbor --docker-server=$HR_REGISTRY --docker-username=$HR_REGISTRY_USER --docker-password=$HR_REGISTRY_PASSWORD --docker-email=$GITLAB_USER_EMAIL --dry-run=true -o yaml | kubectl replace --force -f -
    - cat ./packages/main/k8s/service-main.yml | envsubst | kubectl apply -f -
    - cat ./packages/main/k8s/deployment-main.yml | envsubst | kubectl apply -f -
    - cat ./packages/main/k8s/ingress-main.yml | envsubst | kubectl apply -f -

deploy:dev:
  environment:
    name: kyc-staging
  dependencies: []
  variables:
    REPLICAS: 1
  only:
    refs:
      - /^lerna-.*/
  <<: *base_deploy
